### ISSUE TITLE
Possible issue when trying to install latest with go install

### ISSUE THREAD

**Issue by glahdou** [jahvon/flow#123]
### Bug Summary

How to replicate:

`go install github.com/jahvon/flow@latest`

Results in :
```
go: github.com/jahvon/flow@latest (in github.com/jahvon/flow@v0.2.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

Not sure if this is stemming from : 
`replace github.com/charmbracelet/glamour => github.com/jahvon/glamour v0.7.1-patch1`

**Comment by jahvon** [comment]
Yep that's because of the replace. I guess I should have listened to the linting rule that complained about this 😅 
I think the fix for this is to replace all of the charmbracelet imports with the fork that I have so that the replace can be removed.

**Comment by jahvon** [comment]
Seems to be working with the latest release
